-- AlterTable
ALTER TABLE "clients" ADD COLUMN     "email" VARCHAR(255) NOT NULL DEFAULT '';

-- AlterTable
ALTER TABLE "os" ALTER COLUMN "defeitoConstatado" DROP NOT NULL,
ALTER COLUMN "solucao" DROP NOT NULL,
ALTER COLUMN "valServico" DROP NOT NULL,
ALTER COLUMN "valMaterial" DROP NOT NULL,
ALTER COLUMN "total" DROP NOT NULL,
ALTER COLUMN "garantiaPeca" DROP NOT NULL,
ALTER COLUMN "garantiaServico" DROP NOT NULL,
ALTER COLUMN "horaChegada" DROP DEFAULT,
ALTER COLUMN "horaSaida" DROP DEFAULT;
